program: Driver
		
Driver:	
	javac Driver.java 
	javac AbstractGraphADT.java 
	javac AdjacencyListMatrix.java 
	javac AVLTree.java 
	javac BinarySearchTree.java 
	javac BinarySearchTreeWithRotate.java 
	javac BinaryTree.java 
	javac BST.java 
	javac CircularArrayList.java 
	javac DailySection.java 
	javac Date.java 
	javac DepthFirstSearch.java 
	javac DietPlan.java 
	javac Edge.java 
	javac Exercise.java 
	javac ExercisePlan.java 
	javac Food.java 
	javac GetChoiceFromUser.java 
	javac GraphADT.java 
	javac Notebook.java 
	javac Recipe.java 
	javac SearchTree.java 
	javac SkipList.java 
	javac SystemManager.java 
	javac Task.java 
	javac ToDo.java 
	javac UI.java 
	javac User.java
	java Driver
	